Pull Request zum Brunch "Future/tagify roles felder"
McNamara84/gfz-metadata-editor-msl-v2 pull request #153
Opened 2024-11-06 15:26 UTC by Ali-GeoFZ

In diesem Brunch wurden die Roles-Felder von Chosen auf Tagify umgestellt und die Chosen-Einbindung von der "footer" Datei entfernt.

2024-11-06 16:04 UTC, jaFHP requested changes
Im Formular siehts schick aus! Zur Funktionalität zwei Sachen:
- Das Klonen der Reihen funktioniert bei mir nicht.
- Es gibt bei Person und Organisation jeweils nur die gleichen 6 Roles zur Auswahl (forinstitution=2), for institutions=1 bzw. =0 fehlt jeweils im dropdown.

2024-11-08 11:28 UTC, jaFHP commented
Klonen der Zeilen funktioniert jetzt, danke @Ali-GeoFZ ! Bei den Personen bin ich ansonsten auch zufrieden :) 

Bei den Organisationen sollten nicht nur die Institution-Rollen angezeigt werden, sonden auch die mit forinstitutions=2. Im moment sehe ich nur die Rollen mit forInstitutions=1 
Wenn du das noch anpasst, bin ich zufrieden.

Speicherung kann ich nicht testen, weil wir noch den alten Fehler ausm main-branch mit drin haben.

2024-11-08 11:32 UTC, Ali-GeoFZ commented
> Klonen der Zeilen funktioniert jetzt, danke @Ali-GeoFZ ! Bei den Personen bin ich ansonsten auch zufrieden :)
> 
> Bei den Organisationen sollten nicht nur die Institution-Rollen angezeigt werden, sonden auch die mit forinstitutions=2. Im moment sehe ich nur die Rollen mit forInstitutions=1 Wenn du das noch anpasst, bin ich zufrieden.
> 
> Speicherung kann ich nicht testen, weil wir noch den alten Fehler ausm main-branch mit drin haben.

@jaFHP, Von mir kam genau jetzt ein Commit mit der Lösung dafür ;)

2024-11-08 11:33 UTC, jaFHP approved these changes
Frontend sieht gut aus! Approved!

2024-11-08 11:34 UTC, McNamara84 commented
Könnt ihr dann gerne nach main mergen. Die Speicherung testen wir dann ausführlich, wenn die beiden aktuellen Branches nach main gemerged wurden. Meiner ist auch heute noch so weit.

2024-11-08 11:41 UTC, merged