Selenium tests
McNamara84/gfz-metadata-editor-msl-v2 pull request #169
Opened 2024-11-11 12:12 UTC by jaFHP

In diesem Branch wurde ein Selenium-Projekt hinzugefügt (im Ordner tests->SeleniumTests)
Zur Nutzung muss Selenium IDE im Browser installiert werden. Dann das Projekt öffnen und testen :) 

ACHTUNG: der Link im jeweils ersten Command muss auf den jeweiligen lokalen Pfad angepasst werden
![grafik](https://github.com/user-attachments/assets/51d4902d-c4e5-42eb-a7e7-06f0c938ee18)

Enthalten sind erste Tests:
- **AlleFelderausgefüllt** befüllt alle z.Zt. sichtbaren Felder mit validen Werten und speichert
- **Default-Einstellungen** testet, ob inputLanguageDataset Englisch ist und inputRights CC-BY-4.0
- **HilfebuttonsRessourceInformation** testet, ob alle Hilfe-Buttons in der fg Resource Information anklickbar sind und die Überschrift des Modals dem jeweiligen Feld entspricht
- **Lizenzen** testet, ob alle 6 Lizenzen auswählbar sind
- **PflichtfelderAusgefüllt** befüllt alle derzeit zum Speichern nötigen Pflichtfelder (PublicationYear, ResourceType, Title, Author inkl. ORCID, Abstract, DateCreated, Koordinaten mit Description und Daten, Funder)
- **SoftwareLizenzen** testet, ob alle drei Softwarelizenzen ausgewählt werden können, wenn ResourceType=Software (testet NOCH NICHT, ob die anderen Lizenzen _nicht_ auswählbar sind)

2024-11-11 12:58 UTC, McNamara84 requested changes
Öffnen im Selenium-Plugin funktionierte für mich in der neuesten Version von Chrome.
Wenn ich dann aber den ersten Test starte (und ich vermute, das gilt für die anderen auch), wird versucht der MDE2 im Browser unter http://localhost/MDE-MSL/gfz-metadata-editor-msl-v2/ zu öffnen. Da in meiner Entwicklungsumgebung jedoch ein anderes Verzeichnis genutzt wurde, lädt natürlich auch der MDE2 unter dieser URL nicht und der Test wird abgebrochen.

Silenium sollte auch mit relativen Pfadangaben umgehen können und mit Konstanten wie z. B. ${BASE_URL} sollte sich dieses erste kleine Problem umschiffen lassen.

2024-11-11 13:02 UTC, jaFHP commented
> Öffnen im Selenium-Plugin funktionierte für mich in der neuesten Version von Chrome. Wenn ich dann aber den ersten Test starte (und ich vermute, das gilt für die anderen auch), wird versucht der MDE2 im Browser unter http://localhost/MDE-MSL/gfz-metadata-editor-msl-v2/ zu öffnen. Da in meiner Entwicklungsumgebung jedoch ein anderes Verzeichnis genutzt wurde, lädt natürlich auch der MDE2 unter dieser URL nicht und der Test wird abgebrochen.
> 
> Silenium sollte auch mit relativen Pfadangaben umgehen können und mit Konstanten wie z. B. ${BASE_URL} sollte sich dieses erste kleine Problem umschiffen lassen.

dachte darauf hätte ich mit ACHTUNG ausreichend hingewiesen... Aber ja, das geht natürlich eleganter, wenn du das gerne in diesem Pull request haben willst, ziehe ich das vor.

2024-11-11 13:55 UTC, McNamara84 commented
> > Öffnen im Selenium-Plugin funktionierte für mich in der neuesten Version von Chrome. Wenn ich dann aber den ersten Test starte (und ich vermute, das gilt für die anderen auch), wird versucht der MDE2 im Browser unter http://localhost/MDE-MSL/gfz-metadata-editor-msl-v2/ zu öffnen. Da in meiner Entwicklungsumgebung jedoch ein anderes Verzeichnis genutzt wurde, lädt natürlich auch der MDE2 unter dieser URL nicht und der Test wird abgebrochen.
> > Silenium sollte auch mit relativen Pfadangaben umgehen können und mit Konstanten wie z. B. ${BASE_URL} sollte sich dieses erste kleine Problem umschiffen lassen.
> 
> dachte darauf hätte ich mit ACHTUNG ausreichend hingewiesen... Aber ja, das geht natürlich eleganter, wenn du das gerne in diesem Pull request haben willst, ziehe ich das vor.

Natürlich habe ich trotzdem weiter getestet und, sobald man den Pfad angepasst hat, funktionieren die Tests für mich sehr gut. Ich denke, das wird eine großartige Arbeitserleichterung sein, sobald die Pfade zum MDE2 relativ angepasst wurden.

2024-11-11 22:15 UTC, Ali-GeoFZ commented
Bei mir sieht es auch so aus, also alle Teste haben gut funktioniert und die waren alle grün.

2024-11-11 22:16 UTC, Ali-GeoFZ commented
> Bei mir sieht es auch so aus, also alle Teste haben gut funktioniert und die waren alle grün.

Nach der Anpassung der Pfade natürlich

2024-11-13 13:15 UTC, jaFHP commented
Also: Eine variable/dynamische Pfadanpassung ist in Selenium IDE nicht möglich. Stand jetzt müssen die Pfade für die jeweilige lokale Umgebung in jedem Test angepasst werden.
Wenn wir die Tests in github actions automatisieren, sollte das dann überflüssig werden. Ansonsten würde ich erstmal empfehlen, die .side Datei einfach mit euren Pfaden lokal zu speichern, wenn ihr sie lokal nutzen wollt.

2024-11-13 13:19 UTC, McNamara84 approved these changes

2024-11-13 13:21 UTC, merged