Pull request zum Brunch "Feature/main title&formular feedback"
McNamara84/gfz-metadata-editor-msl-v2 pull request #175
Opened 2024-11-14 13:01 UTC by Ali-GeoFZ

In diesem Branch wurden folgende Änderungen umgesetzt:

1. Haupttiteltyp aus Dropdown bei neuen Titelzeilen Entfernt #129 
2. Helptext für Title typen wurde bearbeitet.
3. Feedback-Formular wurde anpasst #128 
4. PHP-Sende-Code der Feedbackfragen anpasst #128

2024-11-14 14:02 UTC, jaFHP requested changes
Feedback-Formular: 
- Die neuen Fragen sind eine echte Verbesserung finde ich
- das Versenden klappt bei mir einwandfrei
- die Verwendung der Sprachvariabeln ist super, und funktioniert
- wen Du noch Zeit hast das umzusetzen (Hat nicht Prio0 finde ich), fänd ich es schön, wenn nach dem Senden noch eine "Danke für Ihr Feedback"-Nachricht zu sehen ist _Vielen Dank für Ihr Feedback, mit dem sie helfen, den Metadateneditor zu verbessern und weiter zu entwickeln_ (oder so kürzer: Vielen Dank!, oder so)

Main Titles:
- in geklonten Zeilen ist Main Title nicht auswählbar, das ist gut wenn: in der Ersten Zeile Main Title ausgewählt bleibt. Wenn Anwender aber den TitleType in der ersten Zeile ändern, wird die Vorgabe nicht erfüllt, dass ein Main Title angegeben werden muss. Das sollten wir verhindern. 
![grafik](https://github.com/user-attachments/assets/15daf9a2-d186-4980-a909-0be23c20db50)

**Vorschlag a:** Das Titeltyp-Feld in der ersten Zeile hat NUR die Auswahlmöglichkeit "Main Title"

**Vorschlag b:** (ich vermute, das ist aufwändiger) Abfragen, ob in einer der Titel-Rows der Titeltyp Main Title vergeben wurde, wenn nicht, dann kann nicht gesendet und gespeichert werden, und es gibt eine entsprechende invalid-Meldung.

2024-11-14 14:28 UTC, Ali-GeoFZ commented
> Feedback-Formular:
> 
> * Die neuen Fragen sind eine echte Verbesserung finde ich
> * das Versenden klappt bei mir einwandfrei
> * die Verwendung der Sprachvariabeln ist super, und funktioniert
> * wen Du noch Zeit hast das umzusetzen (Hat nicht Prio0 finde ich), fänd ich es schön, wenn nach dem Senden noch eine "Danke für Ihr Feedback"-Nachricht zu sehen ist _Vielen Dank für Ihr Feedback, mit dem sie helfen, den Metadateneditor zu verbessern und weiter zu entwickeln_ (oder so kürzer: Vielen Dank!, oder so)
> 
> Main Titles:
> 
> * in geklonten Zeilen ist Main Title nicht auswählbar, das ist gut wenn: in der Ersten Zeile Main Title ausgewählt bleibt. Wenn Anwender aber den TitleType in der ersten Zeile ändern, wird die Vorgabe nicht erfüllt, dass ein Main Title angegeben werden muss. Das sollten wir verhindern.
>   ![grafik](https://private-user-images.githubusercontent.com/167227411/386220694-15daf9a2-d186-4980-a909-0be23c20db50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1OTMzNzQsIm5iZiI6MTczMTU5MzA3NCwicGF0aCI6Ii8xNjcyMjc0MTEvMzg2MjIwNjk0LTE1ZGFmOWEyLWQxODYtNDk4MC1hOTA5LTBiZTIzYzIwZGI1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxNDA0MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZWNkNTBhNjg2MmExZTVmZDhkODlkNmVhY2JkYzU2NWFmZmFlZWVmZDViM2IxYmU5NWExNjY2YWE3MGRiMzBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mZi-pRh8d0iTs9obCQSZpemy_hhbxOON6IHjexptEPY)
> 
> **Vorschlag a:** Das Titeltyp-Feld in der ersten Zeile hat NUR die Auswahlmöglichkeit "Main Title"
> 
> **Vorschlag b:** (ich vermute, das ist aufwändiger) Abfragen, ob in einer der Titel-Rows der Titeltyp Main Title vergeben wurde, wenn nicht, dann kann nicht gesendet und gespeichert werden, und es gibt eine entsprechende invalid-Meldung.

Danke für deinen tollen Review!

* Ich finde deinen Vorschlag, die Nutzer:innen um ein Dankeschön zu bitten, sehr gut und werde versuchen, ihn heute umzusetzen.
* Bei den Titel-Vorschlägen bevorzuge ich Vorschlag A. Vorschlag B können wir nicht umsetzen, da die Nutzer:innen nicht verpflichtet sind, einen Titeltyp auszuwählen; es handelt sich also nicht um ein Pflichtfeld.

2024-11-15 11:06 UTC, McNamara84 commented
@Ali-GeoFZ , kannst du bitte noch die buttons.js nach JSDoc dokumentieren und beim Merge darauf achten, dass du die Code-Dokumentation bzw. Kommentare in der send_feedback_mail.php (angepasst an deine Änderungen) übernimmst? Danke!

2024-11-20 13:39 UTC, McNamara84 commented
> einmal Speichern funktioniert mit den richtigen titleTypes, danach habe ich Fehler. Glaube das liegt an Merge-Conflicts. Wir hatten doi=leer mal als Problem.

Ja, das liegt daran, dass der Branch schon etwas älter ist.

2024-11-20 13:51 UTC, merged