API Anpassungen
McNamara84/gfz-metadata-editor-msl-v2 pull request #179
Opened 2024-11-17 05:06 UTC by McNamara84

**Draft zur Anpassung der API:**
- Fixed #123 
- Fixed #166

2024-11-18 12:53 UTC, jaFHP reviewed
- issue #123 es werden weder die (leeren) descriptions, noch synonyme angezeigt (klar das geht nicht, weil im Gesamtvokabular keine sind) stattdessen die (tw. falschen) Namen "Geologicalage"

- issue #166  ist nicht gefixed. Die Top Terms heißen weiterhin anders als sie sollten, trotz richtigen Werten in der json-Datei (??? mache ich was falsch?, wie kann das sein?) in der readme stehen auch noch die falschen Werte (zwar mit den Hinweis Deprecated, würde ich aber trotzdem löschen)
![grafik](https://github.com/user-attachments/assets/848cab49-3047-4aca-8f8d-c8b7921adf61)

- auch einen Filter für die NOT APPLICABLE nodes (issue #13) finde ich nicht. 

Übersehe ich grade irgendwas dummes? Hab eben nochmal das repository refreshed..., /update/vocabs/msl liefert mir: {"error":"No vocabulary version found"}

2024-11-18 16:55 UTC, McNamara84 commented
Danke für dein Feedback! Tatsächlich habe ich den Filter für NOT APPLICABLE vergessen zu comitten, aber ich hatte die Änderungen noch gestaged, weil ich ihn noch dokumentieren wollte. Commit folgt gleich und dann auch gleich nach PHPDoc.
Den rest haben wir ja direkt geklärt und deshalb würde ich das gleich nochmal zur Review einreichen.

2024-11-19 10:24 UTC, jaFHP requested changes
Keine Ahnung was da gestern los war...

- Descriptions: Im Moment wird der Text bei Mouseover angezeigt, wenn die Descriptions und Synonyme angezeigt werden sollen, sollte das Mouseover z.Zt. aber leer sein, da description und synonyms leer bzw. nicht vorhanden sind
- Top Terms werden richtig angezeigt, juhu!
-NOT APPLICABLE nodes werden bei den GCMD Science Keywords weiterhin nicht angezeigt, der Filter funktioniert also und jetzt ist es eleganter gelöst!
- /vocabs/sciencekeywords funktioniert
- instrument keywords ist nicht dokumentiert, macht vllt auch Sinn, weil wirs hier nicht nutzen, aber ist so halt schlecht nutzbar (ich z.B. finde grade nicht raus, wie ich die API testen kann), ich bin daher für die Aufnahme in die Doku. Auch damit du das nicht umsonst gemacht hast, erhöht Nachnutzungsmöglichkeiten usw.
- gleiches bei den platform keywords
- generell wäre ich auch dafür, den Code aufzuräumen (inkl. v.a. die Readme), wenn alle APIs auf V2 sind

2024-11-19 12:19 UTC, McNamara84 commented
> * Descriptions: Im Moment wird der Text bei Mouseover angezeigt, wenn die Descriptions und Synonyme angezeigt werden sollen, sollte das Mouseover z.Zt. aber leer sein, da description und synonyms leer bzw. nicht vorhanden sind

Also mit dem letzten Commit habe ich nochmal klar im Code vermerkt, dass grundsätzlich der Schlüssel `description` verwendet wird, aber quasi als Fallback der Schlüssel `text` für die Mouseover-Anzeige genutzt wird, wenn `description` leer ist.

2024-11-19 12:26 UTC, McNamara84 commented
> * instrument keywords ist nicht dokumentiert, macht vllt auch Sinn, weil wirs hier nicht nutzen, aber ist so halt schlecht nutzbar (ich z.B. finde grade nicht raus, wie ich die API testen kann), ich bin daher für die Aufnahme in die Doku. Auch damit du das nicht umsonst gemacht hast, erhöht Nachnutzungsmöglichkeiten usw.
> * gleiches bei den platform keywords

Aktuell existiert nur ein APIv2-Endpunkt `/update/vocabs/gcmd` und dieser aktualisiert alle drei GCMD-Thesauri auf einmal (Ausführungszeit ~1min). Bitte diesen Endpunkt testen.
Der APIv2-Endpunkt, den du getestet hast, war `/vocabs//sciencekeywords`. Dieser wurde in diesem Sprint gar nicht
 bearbeitet (aber offensichtlich funktioniert er). Er ist eigentlich für zukünftige Anwendungen bzw. Anwendungen von Drittanbietern (z. B. für @Daetha ) um das Vokabular in der selben Form nachnutzen zu können. Gerade wenn wir mal irgendwann den MDE2 für Datenkurtaor:innen neu aufsetzen, dann kann das dort gut nachgenutzt werden.
Ich werde aber mit meinem nächsten Commit die APIv2-Dokumentation überarbeiten damit das klarer wird.

2024-11-19 12:32 UTC, McNamara84 commented
> * generell wäre ich auch dafür, den Code aufzuräumen (inkl. v.a. die Readme), wenn alle APIs auf V2 sind

Gerne. Die Hinweise auf die alte APIv1 will ich natürlich auch aus der ReadMe entfernen. Aber erst, wenn die API vollständig nach APIv2 portiert wurde.

Ich fordere gleich mal eine neue Review bei dir an.

2024-11-19 12:45 UTC, jaFHP commented
> > * Descriptions: Im Moment wird der Text bei Mouseover angezeigt, wenn die Descriptions und Synonyme angezeigt werden sollen, sollte das Mouseover z.Zt. aber leer sein, da description und synonyms leer bzw. nicht vorhanden sind
> 
> Also mit dem letzten Commit habe ich nochmal klar im Code vermerkt, dass grundsätzlich der Schlüssel `description` verwendet wird, aber quasi als Fallback der Schlüssel `text` für die Mouseover-Anzeige genutzt wird, wenn `description` leer ist.

argh, ich hab mich unklar ausgedrückt: für meinen Geschmack bietet das Mouseover mit dem Text keinen Mehrwert. Wenn es keine Description oder Synonyme gibt, dann braucht es dort keinen Text finde ich.

2024-11-19 12:54 UTC, McNamara84 commented
> > > * Descriptions: Im Moment wird der Text bei Mouseover angezeigt, wenn die Descriptions und Synonyme angezeigt werden sollen, sollte das Mouseover z.Zt. aber leer sein, da description und synonyms leer bzw. nicht vorhanden sind
> > 
> > 
> > Also mit dem letzten Commit habe ich nochmal klar im Code vermerkt, dass grundsätzlich der Schlüssel `description` verwendet wird, aber quasi als Fallback der Schlüssel `text` für die Mouseover-Anzeige genutzt wird, wenn `description` leer ist.
> 
> argh, ich hab mich unklar ausgedrückt: für meinen Geschmack bietet das Mouseover mit dem Text keinen Mehrwert. Wenn es keine Description oder Synonyme gibt, dann braucht es dort keinen Text finde ich.

So besser?

2024-11-19 13:10 UTC, merged