Pull request für den Brunch 'fix-roles-save-db'
McNamara84/gfz-metadata-editor-msl-v2 pull request #240
Opened 2024-12-02 11:55 UTC by Ali-GeoFZ

Liebe @jaFHP in diesem Brunch wurde den Fehler bei der Speicherung der Rollen von "Contributors" in der Datenbank behoben (fixed #229) 

Es wurde eine JSON-Dekodierung für die Rollen-Eingabe hinzugefügt

2024-12-02 12:05 UTC, jaFHP requested changes
Die Speicherung der Roles funktioniert bei mir, Danke!

Allerdings scheitern die php-Tests. Bevor ich mich da reindenke: @McNamara84 wie schnell kannst du sagen, woran das liegt?

2024-12-02 12:10 UTC, Ali-GeoFZ commented
@jaFHP, Danke! Ich denke, das liegt an den Änderungen im Speichercode der "Contributors", die ich gemacht hab

2024-12-02 12:11 UTC, jaFHP commented
> @jaFHP, Danke! Ich denke, das liegt an den Änderungen im Speichercode der "Contributors", die ich gemacht hab

Ja, klar. Aber ich weiß nicht, wie das schnell gefixed wird und würde mich ungern reindenken, wenn Holger schneller weiterhelfen kann.

2024-12-02 12:13 UTC, McNamara84 commented
Moment, ich schaue mir das an. Könnt ihr mir bitte derweil eine knallharte Review verpassen?

2024-12-02 12:25 UTC, McNamara84 commented
> @jaFHP, Danke! Ich denke, das liegt an den Änderungen im Speichercode der "Contributors", die ich gemacht hab

Soeben geprüft. Der Test muss überarbeitet werden. Es geht ja nun JSON rein und gespeichert werden nur die Values. Der Test füttert geht aber immer von reinen Strings aus, die eingehen.

2024-12-02 12:31 UTC, jaFHP commented
> Moment, ich schaue mir das an. Könnt ihr mir bitte derweil eine knallharte Review verpassen?

Bin dabei, knallhart dauert nur ein bisschen 😄

2024-12-04 11:59 UTC, jaFHP approved these changes
Speichern funktioniert, Tests sind grün.

Danke, Approved!

2024-12-04 12:47 UTC, merged