Feature: Custom filename for XML download
McNamara84/gfz-metadata-editor-msl-v2 pull request #250
Opened 2024-12-07 03:14 UTC by McNamara84

2024-12-09 10:15 UTC, McNamara84 commented
> Funktioniert einwandfrei!
> 
> Aus NutzerInnensicht würde ich mir noch diese Änderungen wünschen:
> 
> 1. das Modal ist auf Deutsch, alle anderen auf English, ich bin dafür, entweder lang-variablen zu nutzen, oder den User-Dialog einheitlich auf englisch zu machen.
> 2. Ein hinweis darauf, dass eine xml-Datei gespeichert wird fänd ich gut. vielleicht einfach die Endung mit einblenden? verhindert dann auch dataset1.xml.xml oder so.
> 3. Wenn ich das speichern abbreche, ist immer noch diese Info zu sehen:
>    [...]
>    das halte ich für unnötig und etwas verwirrend, ich habe ja auf Abbrechen geklickt.

Danke für die schnelle und gründliche Review!
Bei den Punkten 1 und 3 bin ich ganz bei dir. Punkt 1 habe ich tatsächlich einfach vergessen umzusetzen und Punkt 3 ist auch klar.
Punkt 2 verstehe ich jedoch nicht ganz. Im Form zur Eingabe des Dateinamens (im neuen Modal) ist die Dateiendung ganz klar angegeben hinter dem Eingabefeld. reicht das nicht aus? Soll über das Eingabefeld zusätzlich wirklich noch ein Text?

2024-12-09 13:50 UTC, McNamara84 commented
@jaFHP , dein Feedback (auch das aus dem Daily) habe ich hoffentlich so umgesetzt, wie du das vorgeschlagen hast. Falls es noch weitere Änderungswünsche gibt, lass es mich wissen. Re-Review wird gleich angefordert.

2024-12-10 11:47 UTC, jaFHP requested changes
Funktioniert immer noch einwandfrei und meine Anmerkungen sind gelöst. Ich habe aber noch zwei klitzekleine neue...

1. Den gelb markierten Text empfinde ich als Dopplung und unnötig.
![grafik](https://github.com/user-attachments/assets/fb5966cf-ea11-4078-a5a4-896d516edb78)

2. Die Tooltips für die Buttons (inkl save-Button) sind als Sprachvariablen vorhanden, werden mir aber nicht angezeigt. Entweder rauslöschen, oder anzeigen wäre mein wunsch.

2024-12-10 11:47 UTC, jaFHP commented on lang/en.php
> +    'filenameLabel' => 'Preferred Filename',
filename klein, wenn die Variable wirklich nötig ist

2024-12-10 13:23 UTC, McNamara84 commented
> Funktioniert immer noch einwandfrei und meine Anmerkungen sind gelöst. Ich habe aber noch zwei klitzekleine neue...
> 
> 1. Den gelb markierten Text empfinde ich als Dopplung und unnötig.
> 2. Die Tooltips für die Buttons (inkl save-Button) sind als Sprachvariablen vorhanden, werden mir aber nicht angezeigt. Entweder rauslöschen, oder anzeigen wäre mein wunsch.

Danke für das Feedback! Punkt 1 habe ich nach Rücksprache mit dir gefixt. Für Punkt 2 habe ich mir einen Mittelweg überlegt. Als Mouseover/Tooltip würden mich die Texte nerven. Deshalb habe ich sie als aria-label für alle aktuell funktionierenden Buttons gesetzt. Screenreader lesen dann den Wert von aria-label aus, aber sonst sieht den Text niemand. Wäre diese Lösung für dich okay?

2024-12-10 13:52 UTC, merged